# Generated by Django 4.2.16 on 2025-02-15 09:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("citations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indique si la catégorie est active ou non.",
                verbose_name="Is Active",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                default=False,
                help_text="Un identifiant unique pour l'URL de la catégorie.",
                max_length=100,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="featured",
            field=models.BooleanField(
                default=False,
                help_text="Indique si la citation est mise en avant.",
                verbose_name="Featured",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="likes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Le nombre de likes reçus par la citation.",
                verbose_name="Likes",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                help_text="Le statut de la citation (ex: Draft, Published, Archived).",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Des mots-clés pour faciliter la recherche (séparés par des virgules).",
                max_length=255,
                null=True,
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="views",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Le nombre de fois que la citation a été vue.",
                verbose_name="Views",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Une description de la catégorie.",
                null=True,
                verbose_name="Category Description",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Le nom de la catégorie (ex: Inspiration, Humor, etc.).",
                max_length=100,
                unique=True,
                verbose_name="Category Name",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="author",
            field=models.CharField(
                blank=True,
                help_text="L'auteur de la citation (optionnel).",
                max_length=100,
                null=True,
                verbose_name="Quote Author",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="La catégorie à laquelle la citation appartient.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="citations.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="text",
            field=models.TextField(
                help_text="Le texte de la citation (au moins 10 caractères).",
                validators=[django.core.validators.MinLengthValidator(10)],
                verbose_name="Quote Text",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="L'utilisateur qui a créé la citation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
