# Generated by Django 4.2.16 on 2025-02-20 15:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("citations", "0002_alter_category_options_category_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A description of the category.",
                null=True,
                verbose_name="Category Description",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether the category is active or not.",
                verbose_name="Is Active",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="The name of the category (e.g., Inspiration, Humor, etc.).",
                max_length=100,
                unique=True,
                verbose_name="Category Name",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="A unique identifier for the category's URL.",
                max_length=100,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="author",
            field=models.CharField(
                blank=True,
                help_text="The author of the quote (optional).",
                max_length=100,
                null=True,
                verbose_name="Quote Author",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="The category to which the quote belongs.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="citations.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="featured",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the quote is featured.",
                verbose_name="Featured",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="likes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The number of likes the quote has received.",
                verbose_name="Likes",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                help_text="The status of the quote (e.g., Draft, Published, Archived).",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Keywords to make the quote easier to find (comma-separated).",
                max_length=255,
                null=True,
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="text",
            field=models.TextField(
                help_text="The text of the quote (at least 10 characters).",
                validators=[django.core.validators.MinLengthValidator(10)],
                verbose_name="Quote Text",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created the quote.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="views",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The number of times the quote has been viewed.",
                verbose_name="Views",
            ),
        ),
    ]
